# Generated by Django 5.0.4 on 2024-11-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_like'),
    ]

    operations = [
    ]
